repos:
  # Run the Ruff linter.
  - repo: https://github.com/ambv/black
    # Ruff version.
    rev: 24.1.1
    hooks:
      # Run the black formatter.
      - id: black
        language_version: python3.10
