site_name: bedbase
site_url: https://bedboss.databio.org/
repo_url: https://github.com/bedbase/bedboss
site_logo: img/geofetch_logo_dark.svg
pypi_name: bedbase

nav:
  - Getting started:
    - Introduction: README.md
  - Tutorials:
    - Base Tutorial: tutorial.md
  - How-to Guides:
    - Create bedbase config file: bedbase_config_file
  - Reference:
    - Support: https://github.com/bedbase/bedboss/issues
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio


plugins:
  - search
#  - databio:
#      jupyter_source: "docs_jupyter"
#      jupyter_build: "docs_jupyter/build"
#      usage_template: "docs/usage_template.md"
#      usage_cmds:
#        - "geofetch --help"
